### ISSUE TITLE
Remove node_modules from source

### ISSUE THREAD

**Issue by stevenfollis** [Azure-Samples/app-service-api-apps-quickstart-nodejs#1]
Removing the node_modules folder from source should cut down on repo size. Also should probably use a .gitignore file optimized for Node solutions

**Comment by dpwolfe** [comment]
Since the repo is so new and this is just a sample, I'd recommend doing a rebase after node_modules is deleted to really reclaim that space. If the git commands would trip you up, check out this tool which makes it easy after node_modules is deleted: https://rtyley.github.io/bfg-repo-cleaner/

Also, here is github's default .gitignore for Node that you can copy. It is what would have been added by default when creating the repo if that option was selected: https://github.com/github/gitignore/blob/master/Node.gitignore

**Comment by dpwolfe** [comment]
@stevenfollis put up a PR, it has merge conflicts right now... probably some more changes in the node_modules folder is all :
https://github.com/Azure-Samples/app-service-api-apps-quickstart-nodejs/pull/2
@bradygaster (friendly ping in case you aren't getting any notifications otherwise).

**Comment by bradygaster-zz** [comment]
@stevenfollis this isn't a sample. it's actually a compartmentalized, very-deliberately-including-node-modules folder sort of thing. Also no .gitignore was deliberate. This is very possibly a point-in-time thing due to the very specific nature of this repository. 

In other times, I would totally agree with you and not do this. :)

**Comment by stevenfollis** [comment]
@bradygaster Doh! My bad; thanks for the update!
